baseURL: 'https://suba327777.github.io/my-blog/'
languageCode: 'en-us'
title: 'mena log'
theme: 'PaperMod'

enableEmoji: true
enableRobotsTXT: true

publishDir: "docs"

params:
  #    env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: mena
  keywords: [""]
  author: suba
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "mena.png"
    favicon16x16: "mena.png"
    favicon32x32: "mena.png"
    apple_touch_icon: "mena.png"
    safari_pinned_tab: "mena.png"

  label:
    text: "✋ Home"
    iconHeight: 35
  # homeInfoParams:
  #   Title: "記事"
  #   Content: >
  #     メモ等を書いてます

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/suba327777/my-blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link


  # for search
  # https://fusejs.io/api/options.html
  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 10
    - identifier: tags
      name: tags
      url: /tags
      weight: 25
